# Generated by Django 2.2.12 on 2020-04-03 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_series', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Серия карты')),
                ('card_number', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Номер карты')),
                ('card_issue_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата выпуска карты')),
                ('card_activity_end_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Дата окончания активности карты')),
                ('datetime_of_use', models.SmallIntegerField(choices=[(0, 1), (1, 6), (2, 12)], default=2, verbose_name='Срок использования карты')),
                ('sum_on_card', models.IntegerField(default=0, verbose_name='Сумма на карте')),
                ('card_status', models.SmallIntegerField(choices=[(0, 'Карта не активирована'), (1, 'Карта активирована'), (2, 'Карта просрочена')], default=0, verbose_name='Статус карты')),
            ],
        ),
    ]
